build: "hg19"
liftover: "/Users/rmvpaeme/liftOver"
chain: "/Users/rmvpaeme/GRCh37_to_GRCh38.chain.gz"
sites: "/Users/rmvpaeme/Repos/2003_CelFiE/tubestudy_data/rrbs_tims_with_celfie/wgbs_tims_rrbs_sites_500_hg38.txt"
reference: "/Users/rmvpaeme/Repos/2003_CelFiE/tubestudy_data/rrbs_tims_with_celfie/wgbs_tims_rrbs_sites_500_hg38_merged.txt"
referenceLabels: "/Users/rmvpaeme/Repos/2003_CelFiE/celfiePipeline/reference_dataset_WGBS_tissues/celfie_reference_file_key_WGBS_tissues.txt"
reference_tims_summed: "/Users/rmvpaeme/Repos/2003_CelFiE/tubestudy_data/rrbs_tims_with_celfie/wgbs_tims_rrbs_500_summed.txt"
celfie_em: "/Users/rmvpaeme/Repos/2003_CelFiE/celfiePipeline/celfie/EM/em.py"
sumbylist: "/Users/rmvpaeme/Repos/2003_CelFiE/celfie/shell_scripts/sum_by_list.py"
